feat: create permission resource
vsabella/terraform-provider-mssql pull request #4
Opened 2024-03-12 08:44 UTC by tdien105

2024-03-13 08:55 UTC, locmai requested changes
Besides the gofmt errors

2024-03-13 08:55 UTC, locmai commented on internal/provider/mssql_permission_resource.go
> +				Computed:            true,
```suggestion
			"permission": schema.StringAttribute{
				MarkdownDescription: "Name of database-level SQL permission. For full list of supported permissions, see [docs](https://learn.microsoft.com/en-us/sql/t-sql/statements/grant-database-permissions-transact-sql?view=azuresqldb-current#remarks)",
				Required:            true,
```

Either updating the MssqlPermissionResourceModel struct to ``Permissions []types.String `tfsdk:"permissions"` `` or this to ``permission``. The Computed will set this to be read-only data.

2024-03-13 08:55 UTC, locmai commented on internal/mssql/sqlclient.go
> +	cmd := fmt.Sprintf("GRANT %s TO [%s]", permission_name, principal_id)
This got a syntax error when executed:

```
mssql: Incorrect syntax near the keyword '<permissions>'.
```

2024-05-03 07:17 UTC, vsabella commented
integrating into #9

2024-05-03 07:17 UTC, closed without merging